=== SchemaStore/schemastore/src/schemas/json/nuget-project-3.3.0.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://json.schemastore.org/nuget-project-3.3.0.json",
  "definitions": {
    "configType": {
      "type": "object",
      "properties": {
        "dependencies": {
          "$ref": "#/definitions/dependencies"
        },
        "imports": {
          "type": "string"
        }
      }
    },
    "dependencies": {
      "description": "A list of dependencies.",
      "type": "object",
      "additionalProperties": {
        "type": ["string", "object"],
        "properties": {
          "version": {
            "type": "string"
          },
          "type": {
            "type": "string",
            "default": "default",
            "enum": ["default", "build"]
          }
        }
      }
    }
  },
  "properties": {
    "dependencies": {
      "$ref": "#/definitions/dependencies"
    },
    "frameworks": {
      "type": "object",
      "additionalProperties": {
        "$ref": "#/definitions/configType"
      }
    },
    "runtimes": {
      "type": "object",
      "description": "A list of supported runtime platforms.",
      "properties": {
        "win10-arm": {
          "type": "object"
        },
        "win10-arm-aot": {
          "type": "object"
        },
        "win10-x86": {
          "type": "object"
        },
        "win10-x86-aot": {
          "type": "object"
        },
        "win10-x64": {
          "type": "object"
        },
        "win10-x64-aot": {
          "type": "object"
        }
      }
    },
    "supports": {
      "type": "object",
      "description": "A list of supported target frameworks.",
      "additionalProperties": {
        "type": "object",
        "description": "A supported target framework."
      }
    }
  },
  "title": "JSON schema for NuGet project.json files",
  "type": "object"
}

=== SchemaStore/schemastore/src/test/nuget-project/fullsample.json
{
  "supports": {
    "net46.app": { },
    "uwp.10.0.app": { },
    "dnxcore50.app": { }
  },
  "dependencies": {
    "Microsoft.NETCore.UniversalWindowsPlatform": "5.0.0"
  },
  "frameworks": {
    "uap10.0": {
      "imports": "portable-net452+win81",
      "dependencies": {
        "Newtonsoft.Json": "6.0.4"
      }
    }
  },
  "runtimes": {
    "win10-arm": { },
    "win10-arm-aot": { },
    "win10-x86": { },
    "win10-x86-aot": { },
    "win10-x64": { },
    "win10-x64-aot": { }
  }
}
